In [1]:
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import shortest_path

def sdgraph(W,m):
              graph =w
              graph = shortest_path(graph,method=m, directed=False)
              return graph


In [8]:
import dionysus as d
import numpy as np 
from scipy.spatial.distance import pdist ,squareform
W=np.array([[0 ,1 ,0],[1, 0 ,0],[0, 0 ,0]])
m='auto'
W=sdgraph(W,m)
sq_dist = squareform(W)
f = d.fill_rips(sq_dist, 2, np.max(W)) # creates the k-skeleton of the Vietoris-Rips filtration (edge weight filtration) of the graph
m = d.homology_persistence(f) # calculates persistent homology
dgms = d.init_diagrams(m, f)
for i, dgm in enumerate(dgms):
        print("Dimension:", i)
        for p in dgm:
            print(p)
d.plot.plot_bars(dgms[0],order = 'birth', show = True)
plt.show()

Dimension: 0
(0,inf)
(0,1)
(0,inf)
Dimension: 1
Dimension: 2


<Figure size 640x480 with 1 Axes>

NameError: name 'plt' is not defined

In [5]:
w=np.array([[0 ,1 ,0],[1, 0 ,0],[0, 0 ,0]])
print(w)

[[0 1 0]
 [1 0 0]
 [0 0 0]]


In [7]:
print(sdgraph(w,'auto'))

[[ 0.  1. inf]
 [ 1.  0. inf]
 [inf inf  0.]]
